CREATE TABLE IF NOT EXISTS special_member_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    acc_id INT(11) NOT NULL,
    company_name VARCHAR(190) NOT NULL DEFAULT '',
    shop_name VARCHAR(190) NOT NULL DEFAULT '',
    contact_name VARCHAR(190) NOT NULL DEFAULT '',
    email VARCHAR(190) NOT NULL DEFAULT '',
    tel VARCHAR(50) NOT NULL DEFAULT '',
    zip VARCHAR(20) NOT NULL DEFAULT '',
    address_line1 VARCHAR(190) NOT NULL DEFAULT '',
    address_line2 VARCHAR(190) NOT NULL DEFAULT '',
    address_line3 VARCHAR(190) NOT NULL DEFAULT '',
    website_url VARCHAR(255) NOT NULL DEFAULT '',
    business_type VARCHAR(190) NOT NULL DEFAULT '',
    notes TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    requested_at DATETIME NOT NULL,
    reviewed_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_special_member_requests_acc_id (acc_id),
    KEY idx_special_member_requests_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
